### ISSUE TITLE
Cannot generate font files

### ISSUE THREAD

**Issue by Crimone** [VdustR/font-splitter#16]
Thank you for making this tool. But now this tool does not work correctly, it seems to be related to the update of the es-abstract package, I can't be sure.

```
Calculating...
C:\Users\Crimone\AppData\Roaming\npm\node_modules\font-splitter\node_modules\es-abstract\5\CheckObjectCoercible.js:11
                throw new $TypeError(optMessage || ('Cannot call method on ' + value));
                ^

TypeError: Cannot call method on null
    at Object.CheckObjectCoercible [as RequireObjectCoercible] (C:\Users\Crimone\AppData\Roaming\npm\node_modules\font-splitter\node_modules\es-abstract\5\CheckObjectCoercible.js:11:9)
    at matchAll (C:\Users\Crimone\AppData\Roaming\npm\node_modules\font-splitter\node_modules\string.prototype.matchall\implementation.js:24:13)
    at getFontName (C:\Users\Crimone\AppData\Roaming\npm\node_modules\font-splitter\src\app.js:25:10)
    at genSubsets (C:\Users\Crimone\AppData\Roaming\npm\node_modules\font-splitter\src\app.js:203:32)
    at Object.<anonymous> (C:\Users\Crimone\AppData\Roaming\npm\node_modules\font-splitter\bin\font-splitter:59:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) 
```

**Comment by VdustR** [comment]
Sorry for the very late follow-up, and thank you for reporting this.

This issue came from the legacy npm/Node.js implementation and its dependency stack. The project has moved to a Python package as of v0.2.0, and the current release is v0.2.1. The new implementation uses FontTools directly from Python and no longer uses the old `es-abstract` / `string.prototype.matchall` path shown in this stack trace.

The npm package is now deprecated and only contains the legacy implementation. Please install the current package from the GitHub release tag instead:

```sh
python -m pip install "font-splitter @ git+https://github.com/VdustR/font-splitter.git@v0.2.1"
```

I’m closing this because the affected implementation path has been removed. If you can still reproduce a generation failure with v0.2.1, please open a new issue with the font file, command, and output.
